server:
  port: 8800

spring:
  application:
    name: AuthService

  boot:
    admin:
      client:
        url:
          - http://localhost:1111/

  datasource:
    url: jdbc:mysql://localhost:3306/demo1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true
jwt:
  secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
