spring:
  application:
    name: DataBaseService
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Optional: Format SQL for better readability
  jpa.properties:
    hibernate.format_sql: true
server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
